### REGISTER
POST http://localhost:3000/api/auth/register
Accept: application/json
Content-Type: application/json

{
  "nim":"a11.2022.14616",
  "username":"jamal",
  "password":"jamal123",
  "email":"jamal@gmail"
}


### LOGIN
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "nim":"a11.2022.14616",
  "password":"jamal123"
}

### CURRENT USER
GET http://localhost:3000/api/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaW0iOiJhMTEuMjAyMi4xNDYxNiIsImlzcyI6ImtvcmllYnJ1aCIsImV4cCI6MTczMjE3ODA3MX0.r88rf4yX-G5Xsri7Jvs-tmQPOhQwuDuWW6uNVJH2SAI