### GET request to example server
### LOGIN
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "nim_dinus":"0024fc24720ea15ae00c812a6eb8e866",
  "pass_mhs":"atur sendiri lah"
}


### TEST STATUS STUDENT
GET https://localhost:3000/api/students/status
Accept: application/json
Content-Type: application/json
Authorization: Bearere yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaW1fZGludXMiOiI0Y2Q0ODllZjY2OTdhNmIzY2RmNzkwZjg0NzRlYzQ0MyIsImlzcyI6ImtvcmllYnJ1aC5ha2FKYW1hbCIsImV4cCI6MTczNDQ1NTgzMn0.NRXsS2zjgkgDiWauRVynA6bG_YSPrEfObAQaChGWulA


###
### TEST STATUS STUDENT
PUT https://localhost:3000/api/students/class
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaW1fZGludXMiOiI0Y2Q0ODllZjY2OTdhNmIzY2RmNzkwZjg0NzRlYzQ0MyIsImlzcyI6ImtvcmllYnJ1aC5ha2FKYW1hbCIsImV4cCI6MTczNDQ1NTgzMn0.NRXsS2zjgkgDiWauRVynA6bG_YSPrEfObAQaChGWulA

{
  "kelas": 100
}
