### GET request to example server
### LOGIN
POST http://localhost:3000/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "nim_dinus":"4cd489ef6697a6b3cdf790f8474ec443",
  "pass_mhs":"atur sendiri lah"
}


### TEST STATUS STUDENT
GET https://localhost:3000/api/students/status
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaW1fZGludXMiOiJkNzNjNzY0YmU3ZjdkYWUzZDk3N2MxNjUwMmE0MTJkYyIsImlzcyI6ImtvcmllYnJ1aC5ha2FKYW1hbCIsImV4cCI6MTczNDQ0ODgwNH0.JVmyb_K89B1_pfC16DhLAw1z-En7tufdlhk2Tl7ICW0


###