services:
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'krs_management'
      MYSQL_USER: 'korie'
      MYSQL_PASSWORD: 'korie123'
      MYSQL_ROOT_PASSWORD: 'korie123'
      MAX_CONNECTIONS: "1000"
    volumes:
      - mysql-db:/var/lib/mysql
    healthcheck: # Tambahkan healthcheck
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-db:
    container_name: redis-db
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server"] # Menjalankan Redis tanpa password
    healthcheck: # Tambahkan healthcheck
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      mysql-db:
        condition: service_healthy
      redis-db:
        condition: service_healthy
    restart: always

volumes:
  mysql-db: